//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchoolYear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int eventID { get; set; }
        public int submitterID { get; set; }
        public Nullable<int> classID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime eventDate { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Person Person { get; set; }
    }
}
