//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchoolYear.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int lessonID { get; set; }
        public int teacherID { get; set; }
        public int courseID { get; set; }
        public int classID { get; set; }
        public Nullable<int> roomID { get; set; }
        public System.DateTime datetimeFirstLesson { get; set; }
        public Nullable<System.DateTime> datetimeSecondLesson { get; set; }
        public Nullable<System.DateTime> datetimeThirdLesson { get; set; }
        public Nullable<System.DateTime> datetimeFourthLesson { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Course Cours { get; set; }
        public virtual Room Room { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
